import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

import {
  faFolder,
  faFolderOpen,
  faFile,
  faMagnifyingGlass,
  faCodeBranch,
  faPlay,
  faBug,
  faPuzzlePiece,
  faGear,
  faRobot,
  faBell,
  faMinus,
  faSquare,
  faXmark,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faTerminal,
  faPlus,
  faBroom,
  faEye,
  faEyeSlash,
  faTrash,
  faPen,
  faTags,
  faCloud,
  faClock,
  faRotateRight,
  faCodeCommit,
  faImage,
  faCommentDots,
  faEllipsisVertical,
  faCheck,
  faUpload,
  faGlobe,
} from '@fortawesome/free-solid-svg-icons';
import { faClone, faClock as farClock } from '@fortawesome/free-regular-svg-icons';

library.add(
  faFolder,
  faFolderOpen,
  faFile,
  faMagnifyingGlass,
  faCodeBranch,
  faPlay,
  faBug,
  faPuzzlePiece,
  faGear,
  faRobot,
  faBell,
  faMinus,
  faSquare,
  faXmark,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faTerminal,
  faPlus,
  faBroom,
  faEye,
  faEyeSlash,
  faTrash,
  faPen,
  faTags,
  faCloud,
  faClock,
  faRotateRight,
  faCodeCommit,
  faImage,
  faCommentDots,
  faEllipsisVertical,
  faCheck,
  faUpload,
  faGlobe,
  faClone,
  farClock,
);

export { FontAwesomeIcon };

